import { defineConfig } from "orval";
import { createOrvalConfig } from "@store/orval-config";

// Input spec: the static OpenAPI file generated by `npm run swagger:export -w apps/store-api`.
// This keeps generation reproducible offline and in CI (no running server). For live-server
// generation instead, pass `inputTarget: "http://localhost:3001/api-json"` to the factory.
export default defineConfig(createOrvalConfig({ name: "storeClient" }));
