#!/usr/bin/env node
/**
 * PreToolUse hook (Edit|Write) — protects sensitive / generated files.
 * Blocks edits to:
 *   - .env files (secrets)
 *   - Orval-generated API clients under shared/api/generated/ (regenerated by `npm run generate-api`)
 * Exit code 2 + stderr blocks the tool call and tells Claude why.
 */
let input = '';
process.stdin.on('data', (d) => (input += d));
process.stdin.on('end', () => {
  let payload;
  try {
    payload = JSON.parse(input || '{}');
  } catch {
    process.exit(0); // malformed input — don't block
  }

  const filePath = payload?.tool_input?.file_path || '';
  const normalized = filePath.replace(/\\/g, '/');
  const base = normalized.split('/').pop() || '';

  // .env, .env.local, .env.production ... (but allow .env.example)
  const isEnv = /^\.env(\.[^.]+)?$/.test(base) && base !== '.env.example';
  const isGenerated = /\/shared\/api\/generated\//.test(normalized);

  if (isEnv) {
    console.error(
      `Blocked: editing "${base}" is not allowed — it holds secrets and is gitignored. ` +
        `Update .env.example instead, or ask the user to edit .env manually.`
    );
    process.exit(2);
  }

  if (isGenerated) {
    console.error(
      `Blocked: "${filePath}" is an Orval-generated API file. ` +
        `Hand edits are overwritten — change the OpenAPI source and run "npm run generate-api".`
    );
    process.exit(2);
  }

  process.exit(0);
});
