-- TASK-679 / TASK-1091: a customer's chat may follow several things at once
-- (owner decision 2026-10-07) — one CUSTOMER binding per account and one per
-- guest order. The single partial unique index of TASK-675 allowed one active
-- row per (channel, audience, external_id), so a guest who connected the same
-- Telegram chat to a second order got the FIRST order's row back and the second
-- order would never have notified anyone.
--
-- Generated by `prisma migrate diff --from-config-datasource --to-schema
-- --script` against store_test at the previous migration; nothing hand-written.
--
--   SHOP     — unchanged in effect: one active row per (channel, chat);
--   CUSTOMER — one active row per (channel, chat, account) and one per
--              (channel, chat, order). A row with neither (its account deleted
--              under it: user_id SET NULL) falls under no index — it binds
--              nobody and is never read as anyone's.
--
-- The two plain indexes serve the customer's own «am I connected?» reads.
-- Every new index is looser than (or equal to) the one it replaces, so existing
-- rows satisfy them and no data is touched.

-- DropIndex
DROP INDEX "notification_bindings_active_key";

-- CreateIndex
CREATE INDEX "notification_bindings_user_id_idx" ON "notification_bindings"("user_id");

-- CreateIndex
CREATE INDEX "notification_bindings_order_id_idx" ON "notification_bindings"("order_id");

-- CreateIndex
CREATE UNIQUE INDEX "notification_bindings_shop_active_key" ON "notification_bindings"("channel", "external_id") WHERE (audience = 'SHOP' AND revoked_at IS NULL);

-- CreateIndex
CREATE UNIQUE INDEX "notification_bindings_customer_user_active_key" ON "notification_bindings"("channel", "external_id", "user_id") WHERE (audience = 'CUSTOMER' AND user_id IS NOT NULL AND revoked_at IS NULL);

-- CreateIndex
CREATE UNIQUE INDEX "notification_bindings_customer_order_active_key" ON "notification_bindings"("channel", "external_id", "order_id") WHERE (audience = 'CUSTOMER' AND order_id IS NOT NULL AND revoked_at IS NULL);
