import { Controller, Post } from '@nestjs/common';
import { ApiResponse, DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import type { OpenAPIObject } from '@nestjs/swagger';
import { Test } from '@nestjs/testing';
import { UploadedImageEntity, UploadedImageResponseEnvelope } from './uploaded-image.entity';

/**
 * Contract guard for the upload response entity.
 *
 * WHY THIS SUITE EXISTS. `blurDataUrl` is declared `string | null`, and a UNION has no
 * single `design:type` — TypeScript emits `Object` for it. An `@ApiProperty` that names no
 * `type:` therefore publishes `{"type":"object","nullable":true}`, Orval turns that into
 * `{ [key: string]: unknown } | null`, and a caller writing
 * `<Image blurDataURL={result.data.blurDataUrl} …/>` gets a type error against a server that
 * has always sent a base64 data-URL STRING. The fix is an explicit `type: String` on the
 * decorator, and the only honest way to prove it stays there is to build the REAL OpenAPI
 * document: reading the decorator's own metadata would assert the annotation back at itself,
 * and swagger.json is generated by a separate command that nobody reviews line by line.
 *
 * The throwaway controller is deliberate. `SwaggerModule.createDocument` only emits a schema
 * for a model some route references, and wiring the real `UploadsController` would drag in
 * `PermissionGuard`'s whole dependency graph for a question about two properties.
 */

/**
 * The slice of an emitted OpenAPI schema this suite reads. Declared locally on purpose:
 * `@nestjs/swagger` publishes only its package root through its `exports` map, and re-exports
 * just `OpenAPIObject` there — a deep `@nestjs/swagger/dist/interfaces/…` import compiles
 * under ts-jest and then fails the moment anything typechecks this file with the project's
 * own module resolution.
 */
interface SchemaLike {
  type?: string;
  nullable?: boolean;
  required?: string[];
  $ref?: string;
  properties?: Record<string, SchemaLike>;
}

@Controller('swagger-contract-probe')
class ProbeController {
  @Post()
  @ApiResponse({ status: 201, type: UploadedImageResponseEnvelope })
  probe(): UploadedImageResponseEnvelope {
    return { data: { url: '', blurDataUrl: null } };
  }
}

describe('UploadedImageEntity (OpenAPI contract)', () => {
  let schemas: Record<string, SchemaLike>;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({ controllers: [ProbeController] }).compile();
    const app = moduleRef.createNestApplication();
    await app.init();

    const document: OpenAPIObject = SwaggerModule.createDocument(
      app,
      new DocumentBuilder().setTitle('probe').setVersion('1').build(),
    );
    schemas = (document.components?.schemas ?? {}) as unknown as Record<string, SchemaLike>;

    await app.close();
  });

  it('publishes blurDataUrl as a NULLABLE STRING, never an opaque object', () => {
    const blurDataUrl = schemas.UploadedImageEntity.properties?.blurDataUrl;

    expect(blurDataUrl?.type).toBe('string');
    expect(blurDataUrl?.nullable).toBe(true);
  });

  it('publishes url as a string, with both properties REQUIRED', () => {
    expect(schemas.UploadedImageEntity.properties?.url?.type).toBe('string');
    // Both keys are on every upload response, so neither may drift into `required: false` —
    // Orval would publish that as an optional property the server never actually omits.
    expect(schemas.UploadedImageEntity.required).toEqual(
      expect.arrayContaining(['url', 'blurDataUrl']),
    );
  });

  it('publishes the envelope as a $ref to the entity, not an inline object', () => {
    expect(schemas.UploadedImageResponseEnvelope.properties?.data?.$ref).toBe(
      '#/components/schemas/UploadedImageEntity',
    );
  });

  it('names both models in the document (Orval generates from these schemas)', () => {
    expect(Object.keys(schemas)).toEqual(
      expect.arrayContaining([UploadedImageEntity.name, UploadedImageResponseEnvelope.name]),
    );
  });
});
