import { defineConfig } from "orval";

export default defineConfig({
  storeAdmin: {
    input: {
      // Static OpenAPI spec generated by `npm run swagger:export -w apps/store-api`.
      // This keeps generation reproducible offline and in CI (no running server).
      // For live-server generation instead, switch to "http://localhost:3001/api-json".
      target: "../store-api/swagger.json",
    },
    output: {
      mode: "tags-split",
      target: "src/shared/api/generated/endpoints.ts",
      schemas: "src/shared/api/generated/models",
      client: "react-query",
      httpClient: "axios",
      mock: false,
      clean: true,
      override: {
        mutator: {
          path: "./src/shared/api/instance.ts",
          name: "customInstance",
        },
      },
    },
    hooks: {
      afterAllFilesWrite: "prettier --write",
    },
  },
});
