import { Injectable } from '@nestjs/common';
import { BrandRepository } from '../brand/brand.repository';
import { CategoryRepository } from '../category/category.repository';
import { DeviceRepository } from '../device/device.repository';

/**
 * The id a filter resolves to when the requested slug (or legacy uuid) names
 * nothing (TASK-420).
 *
 * It is a syntactically valid UUID on purpose: `categoryId` reaches a raw
 * `WHERE id = $1` against a `uuid` column in
 * {@link CategoryRepository.findSubtreeIds}, where a non-uuid string is a
 * Postgres error rather than a miss. The nil UUID is never generated by
 * `@default(uuid())`, so it can only ever match zero rows — which is exactly
 * the behaviour an unknown-but-well-formed `?categoryId=` has always had:
 * the filter is APPLIED and matches nothing, producing an empty 200 page
 * rather than a 400 or a silently WIDER listing.
 */
export const UNRESOLVED_FILTER_ID = '00000000-0000-0000-0000-000000000000';

/**
 * Cache-key segment standing in for "this filter named nothing".
 *
 * Every unresolvable value collapses onto this ONE segment because every one of
 * them returns the same empty page — keying them by the raw text instead would
 * let a typo (or a crawler walking dead links) mint an unbounded number of
 * cache entries for identical empty responses.
 *
 * The `!` cannot occur in a generated slug (`generateSlug` keeps only
 * `[a-z0-9-]`), so a real slug can never spell it.
 */
export const UNRESOLVED_FILTER_KEY = '!unknown';

/** The catalogue filter axes as they arrive on the wire (slug + legacy uuid). */
export interface CatalogueFilterQuery {
  /** Canonical form — a category slug (TASK-420). */
  category?: string;
  /** Canonical form — a brand slug. */
  brand?: string;
  /** Canonical form — a device-model slug. */
  device?: string;
  /** Legacy form, still accepted (the admin panel binds these). */
  categoryId?: string;
  brandId?: string;
  deviceModelId?: string;
}

/** One resolved axis: the id the repository filters by + its cache-key segment. */
interface ResolvedAxis {
  id?: string;
  key?: string;
}

/**
 * A catalogue filter resolved to ids, plus the ONE canonical spelling of each
 * axis for the cache key.
 *
 * The two halves exist for different consumers and must not be swapped: the
 * repository only knows ids, and the cache key only knows slugs — so
 * `?brand=apple` and `?brandId=<apple's uuid>` run the same SQL AND read the
 * same cache entry. Keying on whichever spelling the client happened to send
 * would halve the hit rate of every brand/category/device listing (the
 * TASK-541 class of bug).
 */
export interface ResolvedCatalogueFilters {
  categoryId?: string;
  brandId?: string;
  deviceModelId?: string;
  /** Canonical cache-key segment for the category axis (slug, or `!unknown`). */
  categoryKey?: string;
  brandKey?: string;
  deviceKey?: string;
}

/**
 * Resolves the storefront's slug-shaped catalogue filters
 * (`?category=&brand=&device=`) to the ids the repositories query by, and to
 * the canonical slug each axis is cached under (TASK-420).
 *
 * Lives outside `product/` because `/search` narrows on exactly the same three
 * axes and had to migrate together — a "slugs here, uuids there" split is the
 * thing this task exists to remove. Provided (not exported from a module) by
 * both `ProductModule` and `SearchModule`; it is stateless, so a second
 * instance costs nothing and no new module edge is introduced into the
 * Category↔Search forwardRef cycle.
 *
 * Doing this in a service — not a controller and not a repository — keeps the
 * repositories UUID-only: they never learn what a slug is.
 */
@Injectable()
export class CatalogueFilterResolver {
  constructor(
    private readonly categoryRepository: CategoryRepository,
    private readonly brandRepository: BrandRepository,
    private readonly deviceRepository: DeviceRepository,
  ) {}

  /**
   * Resolve all three axes at once (in parallel; an absent axis costs no query).
   *
   * Precedence: the slug param wins when both spellings are sent. The storefront
   * only ever sends one, and a request carrying both is a client bug — resolving
   * it in favour of the canonical form is the reading that does not silently
   * honour a form we are migrating away from.
   */
  async resolve(query: CatalogueFilterQuery): Promise<ResolvedCatalogueFilters> {
    const [category, brand, device] = await Promise.all([
      this.resolveCategory(query.category, query.categoryId),
      this.resolveBrand(query.brand, query.brandId),
      this.resolveDevice(query.device, query.deviceModelId),
    ]);

    return {
      categoryId: category.id,
      brandId: brand.id,
      deviceModelId: device.id,
      categoryKey: category.key,
      brandKey: brand.key,
      deviceKey: device.key,
    };
  }

  /**
   * `activeOnly: false` on purpose. Visibility is enforced downstream — the
   * public listing passes `categoryActiveOnly`, which withdraws a deactivated
   * category's products whatever id resolved (TASK-297) — while the ADMIN
   * listing binds the same DTO and must still be able to filter by a category it
   * has just deactivated. Resolving active-only here would make that category
   * unfilterable in the admin table while changing nothing publicly.
   */
  private async resolveCategory(slug?: string, id?: string): Promise<ResolvedAxis> {
    if (slug) {
      const category = await this.categoryRepository.findBySlug(slug, { activeOnly: false });
      return category ? { id: category.id, key: category.slug } : unresolved();
    }
    if (id) {
      const category = await this.categoryRepository.findById(id);
      return category ? { id: category.id, key: category.slug } : unresolved();
    }
    return {};
  }

  private async resolveBrand(slug?: string, id?: string): Promise<ResolvedAxis> {
    if (slug) {
      const brand = await this.brandRepository.findBySlug(slug);
      return brand ? { id: brand.id, key: brand.slug } : unresolved();
    }
    if (id) {
      const brand = await this.brandRepository.findById(id);
      return brand ? { id: brand.id, key: brand.slug } : unresolved();
    }
    return {};
  }

  private async resolveDevice(slug?: string, id?: string): Promise<ResolvedAxis> {
    if (slug) {
      const model = await this.deviceRepository.findModelBySlug(slug);
      return model ? { id: model.id, key: model.slug } : unresolved();
    }
    if (id) {
      const model = await this.deviceRepository.findModelById(id);
      return model ? { id: model.id, key: model.slug } : unresolved();
    }
    return {};
  }
}

/** A filter that named nothing: applied, matching nothing, keyed as one entry. */
function unresolved(): ResolvedAxis {
  return { id: UNRESOLVED_FILTER_ID, key: UNRESOLVED_FILTER_KEY };
}
