-- TASK-675: binding messenger chats to notifications through one-time deep links.
--
-- Generated by `prisma migrate diff --script` against a database at the previous
-- migration; nothing hand-written. Three new tables, no existing data touched:
--
--   notification_bindings       — which chats receive notifications. Rows are
--                                 never deleted: "disconnect" stamps revoked_at.
--                                 The partial unique index allows one ACTIVE row
--                                 per (channel, audience, external_id) and any
--                                 number of revoked ones, so a disconnected chat
--                                 can be connected again.
--   notification_binding_tokens — sha256 of each one-time `/start` token, 15-min
--                                 TTL, consumed_at set once by the exchange.
--   notification_channel_state  — the getUpdates offset, so a restart neither
--                                 replays nor skips `/start` messages.
--
-- Nothing is backfilled: no chat is connected until someone presses «Старт».

-- CreateEnum
CREATE TYPE "NotificationAudience" AS ENUM ('SHOP', 'CUSTOMER');

-- CreateTable
CREATE TABLE "notification_bindings" (
    "id" TEXT NOT NULL,
    "channel" "NotificationChannel" NOT NULL,
    "audience" "NotificationAudience" NOT NULL,
    "external_id" TEXT NOT NULL,
    "label" TEXT,
    "user_id" TEXT,
    "order_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMP(3),

    CONSTRAINT "notification_bindings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_binding_tokens" (
    "id" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "channel" "NotificationChannel" NOT NULL,
    "audience" "NotificationAudience" NOT NULL,
    "user_id" TEXT,
    "order_id" TEXT,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "consumed_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notification_binding_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_channel_state" (
    "channel" "NotificationChannel" NOT NULL,
    "update_offset" BIGINT NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "notification_channel_state_pkey" PRIMARY KEY ("channel")
);

-- CreateIndex
CREATE INDEX "notification_bindings_channel_audience_revoked_at_idx" ON "notification_bindings"("channel", "audience", "revoked_at");

-- CreateIndex
CREATE UNIQUE INDEX "notification_bindings_active_key" ON "notification_bindings"("channel", "audience", "external_id") WHERE ("revoked_at" IS NULL);

-- CreateIndex
CREATE UNIQUE INDEX "notification_binding_tokens_token_hash_key" ON "notification_binding_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "notification_binding_tokens_expires_at_idx" ON "notification_binding_tokens"("expires_at");

-- AddForeignKey
ALTER TABLE "notification_bindings" ADD CONSTRAINT "notification_bindings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_bindings" ADD CONSTRAINT "notification_bindings_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_binding_tokens" ADD CONSTRAINT "notification_binding_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_binding_tokens" ADD CONSTRAINT "notification_binding_tokens_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;
