import { SeoSnippetPreview } from "@store/store-admin";

// Under the SEO fields of the product / category / page / blog forms. `title`
// is already template-applied (`%s | CaseStore`); the counters measure only the
// operator's own meta fields (60 / 155 recommended).
const HOST = "case-store.com.ua";

const ownTitle = "Чохол Spigen Ultra Hybrid для iPhone 15 Pro";
const ownDescription =
  "Прозорий протиударний чохол із підтримкою MagSafe для iPhone 15 Pro. Захищає кути та камеру. Доставка Новою поштою по Україні.";

export const OwnFields = () => (
  <div style={{ width: "100%" }}>
    <SeoSnippetPreview
      title={`${ownTitle} | CaseStore`}
      titleTier="own"
      description={ownDescription}
      descriptionTier="own"
      url={`${HOST} › products › spigen-ultra-hybrid-iphone-15-pro`}
      rawTitleLength={ownTitle.length}
      rawDescriptionLength={ownDescription.length}
    />
  </div>
);

// Meta fields left blank: title from the product name via the site template,
// description cut from the product text.
export const AutoGenerated = () => (
  <div style={{ width: "100%" }}>
    <SeoSnippetPreview
      title="Павербанк Baseus Magnetic 10000 мА·год | CaseStore"
      titleTier="derived"
      description="Компактний магнітний павербанк на 10 000 мА·год: кріпиться до iPhone через MagSafe, заряджає бездротово до 15 Вт і через USB-C до 20 Вт…"
      descriptionTier="derived"
      url={`${HOST} › products › baseus-magnetic-10000`}
      rawTitleLength={0}
      rawDescriptionLength={0}
    />
  </div>
);

// Operator overshot both limits: the counters turn destructive, the title
// line truncates exactly as a search result would.
const longTitle =
  "Бездротові навушники Apple AirPods Pro 2 з кейсом MagSafe USB-C — купити в Києві з доставкою";
const longDescription =
  "Оригінальні Apple AirPods Pro 2 з активним шумозаглушенням, адаптивним аудіо та кейсом MagSafe з USB-C. Офіційна гарантія 12 місяців, доставка Новою поштою по всій Україні за 1–2 дні, оплата частинами.";

export const OverLimit = () => (
  <div style={{ width: "100%" }}>
    <SeoSnippetPreview
      title={`${longTitle} | CaseStore`}
      titleTier="own"
      description={longDescription}
      descriptionTier="own"
      url={`${HOST} › products › airpods-pro-2-usb-c`}
      rawTitleLength={longTitle.length}
      rawDescriptionLength={longDescription.length}
    />
  </div>
);

// Create mode, nothing typed yet (category form placeholder slug).
export const Empty = () => (
  <div style={{ width: "100%" }}>
    <SeoSnippetPreview
      title=""
      titleTier="empty"
      descriptionTier="empty"
      url={`${HOST} › categories › нова-категорія`}
      rawTitleLength={0}
      rawDescriptionLength={0}
    />
  </div>
);
